default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: plant_pal_development
  username: connorcappello
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost

test:
  <<: *default
  database: plant_pal_test
  username: connorcappello
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
